save_dir: log/efficient1_416_SGD_GFLv2
model:
  arch:
    name: GFL
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite1
      out_stages: [2,4,6]
      activation: ReLU6
      pretrain: True
    fpn:
      name: PAN
      in_channels: [40, 112, 320]
      out_channels: 128
      start_level: 0
      num_outs: 3
    head:
      name: LDGFLv2Head  #or use GFLHead
      num_classes: 80
      input_channel: 128
      feat_channels: 128
      stacked_convs: 3
      #activation: ReLU6
      # silu(x)=x∗σ(x),where σ(x) is the logistic sigmoid.
      #share_cls_reg: True
      octave_base_scale: 8
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: LDLoss
          loss_weight: 0.25
          T: 10 
          alpha: 1
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
      teacher_config: 'config/'
      teacher_model: 'gfl_r101_fpn_mstrain_2x_coco_20200629_200126-dd12f847.pth'
data:
  train:
    name: coco
    img_path: E:/coco17/train2017
    ann_path: E:/coco17/annotations/instances_train2017.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    readall: False
    pipeline:
      perspective: 0.0
      scale: [0.1, 2.0]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.5, 2.0]
      saturation: [0.5, 1.2]
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
    load_mosaic: True
    mosaic_probability: 0.3
    mosaic_area: 9
    mosaic_image_size: 416
  val:
    name: coco
    img_path: E:/coco17/val2017
    ann_path: E:/coco17/annotations/instances_val2017.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 2
  batchsize_per_gpu: 32
  amp_level: 'O3'

schedule:
 # resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.16  #0.1
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 510
    ratio: 0.01
  total_epochs: 150
  lr_schedule:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.1
    patience: 2 #15
    verbose: True
    threshold: 0.00001
    threshold_mode: rel
    cooldown: 0
    min_lr: 0
    eps: 0.000000001 #1e-08

  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 1000

class_names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
              'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant',
              'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog',
              'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
              'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
              'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat',
              'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket',
              'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
              'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
              'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
              'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop',
              'mouse', 'remote', 'keyboard', 'cell_phone', 'microwave',
              'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
              'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']
