#nanodet-m-416
# COCO mAP(0.5:0.95) = 0.235
#             AP_50  = 0.384
#             AP_75  = 0.242
#           AP_small = 0.082
#               AP_m = 0.240
#               AP_l = 0.375
save_dir: log/phase2/ic_resnet50
model:
  arch:
    name: OneStageDetector
    backbone:
      name: Ic_resnet50
      #model_size: 1.0x
      out_stages: [1,2,3,4]
      activation: ReLU
      pretrain: False
      depth: 50
           
    fpn:
      name: PAN
      in_channels: [256, 512, 1024, 2048]
      out_channels: 96
      start_level: 1
      num_outs: 5
    head:
      name: ColanetHead
      num_classes: 80
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: /workspace/Cola/coco17/train2017
    ann_path: /workspace/Cola/coco17/annotations/instances_train2017.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    readall: False
    pipeline:
      perspective: 0.0
      scale: [0.5, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: coco
    img_path: /workspace/Cola/coco17/val2017
    ann_path: /workspace/Cola/coco17/annotations/instances_val2017.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [3]
  workers_per_gpu: 0
  batchsize_per_gpu: 64
  amp_level: 'O3'

schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: AdaBound
    lr: 0.14
    final_lr: 0.1
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 300
  lr_schedule:
    name: MultiStepLR
    milestones: [150,230,275]
    gamma: 0.1
  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 500

class_names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
              'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant',
              'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog',
              'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
              'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
              'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat',
              'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket',
              'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
              'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
              'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
              'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop',
              'mouse', 'remote', 'keyboard', 'cell_phone', 'microwave',
              'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
              'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']
